# Comment on a feature
Feature: Parsing and writing Cucumber features
  When I parse this file
  The different kinds of nodes should be correctly identified
  And preserved when the file is written
  
  
  # Comment on a scenario
  ##/TSATSIKI scenario_id=4     ## This line was generated by Tsatsiki. DO NOT REMOVE
  @some-tag
  @milestone=0.1.0
  Scenario: If I parse and render this file, it should look just like this file
    When I load the feature "features/writing.feature"
    And I render the feature
    Then the result should be identical to "features/writing.feature"
  
  
  @milestone=0.1.0
  Scenario: This scenario has a table
    Given a table:
      | questions                                | answers |
      | Does Tsatsiki taste good with spaghetti? | No      |
      | Does Tsatsiki taste good with gyros?     | Yes     |
  
  
  @milestone=0.1.0
  Scenario: This scenario has a multiline string
    Given a multiline string:
      """
      <html>
        <head></head>
        <body>
          <h1>Tsatsiki!</h1>
        </body>
      </html>
      """
  
  
  @milestone=0.1.0
  Scenario Outline: This scenario has placeholders and examples
    Given a placeholder for an <example>
    Examples:
      | example           |
      | for example       |
      | e.g.              |
      | as in the case of |
  
  
  @tsatsiki-ignore
  Scenario: This scenario is ignored by Tsatsiki
