#!/usr/bin/env ruby

require 'rubygems' unless defined?(Gem)
require 'daemons'

RAILS_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))

server = File.join(RAILS_ROOT, 'lib', 'websocket_server.rb')
options = {
  :dir_mode => :normal,
  :dir => File.join(RAILS_ROOT, 'tmp', 'pids'),
  :log_output => true
}

Daemons.run(server, options)
